"""value db update

Revision ID: 567728f12190
Revises: 6102c1aff9c6
Create Date: 2025-12-11 15:59:18.022529

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "567728f12190"
down_revision = "6102c1aff9c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_latest column as nullable first with default value
    op.add_column(
        "meta_series",
        sa.Column("is_latest", sa.Boolean(), nullable=True, server_default="true"),
    )

    # Update existing rows to set is_latest = True (all existing series are latest by default)
    op.execute("UPDATE meta_series SET is_latest = TRUE WHERE is_latest IS NULL")

    # Now make the column NOT NULL
    op.alter_column(
        "meta_series",
        "is_latest",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default="true",
    )

    # Add other columns (they're nullable)
    op.add_column(
        "meta_series", sa.Column("derived_flag", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "meta_series",
        sa.Column("dependency_calculation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "meta_series", sa.Column("field_name", sa.String(length=255), nullable=True)
    )

    # Create foreign key constraint
    op.create_foreign_key(
        None,
        "meta_series",
        "calculation_log",
        ["dependency_calculation_id"],
        ["calculation_id"],
    )

    # Create indexes
    op.create_index(
        "ix_meta_series_dependency_calc",
        "meta_series",
        ["dependency_calculation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_series_dependency_calculation_id"),
        "meta_series",
        ["dependency_calculation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_series_is_latest"), "meta_series", ["is_latest"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "meta_series", type_="foreignkey")
    op.drop_index(op.f("ix_meta_series_is_latest"), table_name="meta_series")
    op.drop_index(
        op.f("ix_meta_series_dependency_calculation_id"), table_name="meta_series"
    )
    op.drop_index("ix_meta_series_dependency_calc", table_name="meta_series")
    op.drop_column("meta_series", "field_name")
    op.drop_column("meta_series", "dependency_calculation_id")
    op.drop_column("meta_series", "derived_flag")
    op.drop_column("meta_series", "is_latest")
    # ### end Alembic commands ###
