"""remove value db

Revision ID: 6102c1aff9c6
Revises: 20aeddb2378e
Create Date: 2025-12-11 14:38:55.823930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6102c1aff9c6'
down_revision = '20aeddb2378e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_value_data_dependency_calculation_id', table_name='value_data')
    op.drop_index('ix_value_data_is_latest', table_name='value_data')
    op.drop_index('ix_value_data_series_date', table_name='value_data')
    op.drop_index('ix_value_data_series_is_latest', table_name='value_data')
    op.drop_index('ix_value_data_timestamp', table_name='value_data')
    op.drop_table('value_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('dependency_calculation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derived_flag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependency_calculation_id'], ['calculation_log.calculation_id'], name='value_data_dependency_calculation_id_fkey'),
    sa.ForeignKeyConstraint(['series_id'], ['meta_series.series_id'], name='value_data_series_id_fkey'),
    sa.PrimaryKeyConstraint('series_id', 'timestamp', name='value_data_pkey')
    )
    op.create_index('ix_value_data_timestamp', 'value_data', ['timestamp'], unique=False)
    op.create_index('ix_value_data_series_is_latest', 'value_data', ['series_id', 'is_latest'], unique=False)
    op.create_index('ix_value_data_series_date', 'value_data', ['series_id', 'timestamp'], unique=False)
    op.create_index('ix_value_data_is_latest', 'value_data', ['is_latest'], unique=False)
    op.create_index('ix_value_data_dependency_calculation_id', 'value_data', ['dependency_calculation_id'], unique=False)
    # ### end Alembic commands ###


